create table Relative(
	rel_id serial PRIMARY KEY,
	f_name VARCHAR(50),
	l_name VARCHAR(50),
	relation VARCHAR(8),
	u_id INTEGER REFERENCES Users(u_id)
);


insert into Relative (rel_id, f_name, l_name, relation, u_id) values (1, 'Zorine', 'Minchi', 'son', 92);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (2, 'Junia', 'Sabates', 'sister', 91);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (3, 'Jaclyn', 'Moffett', 'brother', 16);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (4, 'Si', 'Steuart', 'grandma', 38);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (5, 'Diannne', 'Benazet', 'sister', 59);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (6, 'Ceil', 'Nuzzti', 'dad', 72);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (7, 'Kurt', 'Samson', 'dad', 19);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (8, 'Lem', 'Martland', 'mom', 57);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (9, 'Asa', 'Kellitt', 'daughter', 33);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (10, 'Bibbye', 'Whellans', 'aunt', 27);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (11, 'Johnathon', 'Greenroad', 'daughter', 53);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (12, 'Monroe', 'Punch', 'son', 50);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (13, 'Ephraim', 'Serchwell', 'mom', 86);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (14, 'Tracie', 'Axtonne', 'dad', 43);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (15, 'Joeann', 'MacHostie', 'grandma', 36);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (16, 'Ag', 'Pert', 'mom', 54);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (17, 'Beverly', 'Want', 'grandpa', 13);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (18, 'Marilin', 'Fermer', 'uncle', 87);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (19, 'Minor', 'Danielczyk', 'aunt', 67);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (20, 'Chlo', 'Drewe', 'daughter', 58);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (21, 'Hall', 'Simak', 'son', 42);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (22, 'Fancie', 'Shewan', 'brother', 43);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (23, 'Bili', 'Escreet', 'sister', 49);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (24, 'Elisabetta', 'Lucken', 'grandma', 49);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (25, 'Gladi', 'Gooddy', 'uncle', 12);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (26, 'Lane', 'Sainsbury-Brown', 'grandma', 51);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (27, 'Shelley', 'Haimes', 'brother', 64);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (28, 'Ravid', 'Kleingrub', 'son', 4);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (29, 'Kessia', 'Tissier', 'brother', 83);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (30, 'Annette', 'Rackam', 'daughter', 70);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (31, 'Bette-ann', 'Godridge', 'brother', 76);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (32, 'Aleda', 'Mucklestone', 'sister', 17);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (33, 'Alfy', 'Duckett', 'daughter', 56);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (34, 'Cristin', 'Eggers', 'uncle', 29);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (35, 'Constancy', 'Francescoccio', 'aunt', 22);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (36, 'Jodie', 'Byrde', 'brother', 31);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (37, 'Kayne', 'Toothill', 'sister', 28);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (38, 'Hali', 'Galilee', 'mom', 60);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (39, 'Trudi', 'Alfwy', 'grandpa', 50);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (40, 'Danny', 'Goadbie', 'daughter', 17);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (41, 'Kennith', 'McCarlie', 'mom', 69);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (42, 'Elias', 'Kitchingman', 'dad', 6);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (43, 'Wendall', 'Cancellieri', 'grandma', 1);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (44, 'Marsiella', 'Stode', 'dad', 10);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (45, 'Rebeka', 'Hoffman', 'son', 95);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (46, 'Glendon', 'Ozintsev', 'sister', 24);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (47, 'Cully', 'Bruyns', 'son', 9);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (48, 'Olag', 'Kenright', 'sister', 25);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (49, 'Haleigh', 'Biskupek', 'sister', 13);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (50, 'Glyn', 'Sangra', 'grandpa', 20);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (51, 'Reynold', 'Trubshawe', 'dad', 30);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (52, 'Brooke', 'Revitt', 'aunt', 62);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (53, 'Phebe', 'Heijnen', 'daughter', 77);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (54, 'Zoe', 'Lound', 'uncle', 50);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (55, 'Guenna', 'Grogor', 'daughter', 81);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (56, 'Kym', 'Blest', 'aunt', 62);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (57, 'Donnell', 'Dossetter', 'son', 87);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (58, 'Genevra', 'Blowing', 'brother', 22);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (59, 'Felicle', 'Metzel', 'brother', 4);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (60, 'Erminie', 'Laweles', 'daughter', 41);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (61, 'Rog', 'Sandford', 'grandpa', 75);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (62, 'Elissa', 'Laybourn', 'sister', 75);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (63, 'Dagny', 'Zamboniari', 'dad', 87);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (64, 'Neille', 'Paroni', 'grandpa', 86);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (65, 'Marianna', 'McDonogh', 'grandpa', 93);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (66, 'Murial', 'Ferries', 'aunt', 99);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (67, 'Ortensia', 'Melia', 'brother', 8);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (68, 'Odelia', 'Fearne', 'brother', 23);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (69, 'Lauree', 'Stalman', 'mom', 52);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (70, 'Kahaleel', 'Edbrooke', 'sister', 94);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (71, 'Giulietta', 'Dalling', 'grandpa', 27);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (72, 'Giacinta', 'Mewis', 'dad', 30);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (73, 'Jaquith', 'Fishe', 'brother', 82);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (74, 'Jinny', 'Clampett', 'daughter', 27);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (75, 'Bibbie', 'Newitt', 'dad', 56);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (76, 'Natal', 'Spenclay', 'uncle', 76);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (77, 'Kendal', 'Inworth', 'sister', 92);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (78, 'Elayne', 'Tidball', 'dad', 89);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (79, 'Marta', 'Ovesen', 'son', 36);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (80, 'Laurence', 'Kelemen', 'grandma', 46);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (81, 'Mortie', 'Fennick', 'brother', 56);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (82, 'Niko', 'Sorel', 'brother', 28);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (83, 'Lionel', 'Sailes', 'aunt', 93);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (84, 'Sibyl', 'McClory', 'aunt', 71);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (85, 'Harwilll', 'Duffet', 'grandma', 60);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (86, 'Fawne', 'Plewes', 'grandma', 62);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (87, 'Matthiew', 'Stoad', 'dad', 59);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (88, 'Lorie', 'Getten', 'sister', 99);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (89, 'Odelinda', 'Dawks', 'grandpa', 82);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (90, 'Patience', 'Lascelles', 'aunt', 87);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (91, 'Edie', 'Merrikin', 'grandpa', 65);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (92, 'Gwen', 'Wetheril', 'uncle', 10);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (93, 'Tabina', 'McGarva', 'daughter', 69);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (94, 'Josy', 'Southeran', 'daughter', 73);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (95, 'Barby', 'Riccardo', 'brother', 61);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (96, 'Putnam', 'Jelleman', 'grandma', 40);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (97, 'Allison', 'Caws', 'grandpa', 37);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (98, 'Kinna', 'Courson', 'grandma', 63);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (99, 'Carine', 'Gerwood', 'grandpa', 23);
insert into Relative (rel_id, f_name, l_name, relation, u_id) values (100, 'Aretha', 'Favell', 'grandpa', 63);

ALTER SEQUENCE Relative_rel_id_seq RESTART WITH 1001;